apiVersion: v1
kind: Service
metadata:
  name: hello-cicd-service
  namespace: hello-cicd-namespace
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: hello-cicd
